//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpoolingCR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carpoolingcrEntities : DbContext
    {
        public carpoolingcrEntities()
            : base("name=carpoolingcrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Mensaje> Mensaje { get; set; }
        public DbSet<Solicitud> Solicitud { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Viaje> Viaje { get; set; }
    }
}
