//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpoolingCR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int ID_MENSAJE { get; set; }
        public int ID_SOLICITUD { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public string MENSAJE1 { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
    }
}
