//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpoolingCR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public Solicitud()
        {
            this.Mensaje = new HashSet<Mensaje>();
        }
    
        public int ID_SOLICITUD { get; set; }
        public int ID_VIAJE { get; set; }
        public int ID_USUARIO { get; set; }
        public string COMENTARIO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<Mensaje> Mensaje { get; set; }
        public virtual Viaje Viaje { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
