//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpoolingCR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public Viaje()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int ID_VIAJE { get; set; }
        public int ID_USUARIO { get; set; }
        public string ORIGEN { get; set; }
        public Nullable<double> LATITUD_ORIGEN { get; set; }
        public Nullable<double> LONGITUD_ORIGEN { get; set; }
        public string DESTINO { get; set; }
        public Nullable<double> LATITUD_DESTINO { get; set; }
        public Nullable<double> LONGITUD_DESTINO { get; set; }
        public Nullable<int> COSTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> HORA { get; set; }
        public Nullable<int> ESPACIOS { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<Solicitud> Solicitud { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
